[package]
name = "actix_webserver"
version = "0.1.1"
edition = "2021"
license = "MIT"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
toml = "0.8.8"
serde = "1.0.188"
serde_derive = "1.0.188"
