[server_config] # Main Actix web server configuration
bind_address = "0.0.0.0" # Bind address to listen on (default: 0.0.0.0 - listen on all interfaces)
port = 8080 # Port the server will listen on (make sure port is open and not already in use)
static_dir = "./static/" # Directory to serve static files from
index_file = "index.html" # Name of default file to serve from static_dir
alt_index = "index2.html" # Name of alternate index file to serve from static_dir (set same as index_file if not needed)
hostname = "localhost" # Hostname for the server to restrict access (prevents hotlinking) (set as empty string to disable)
alt_hostname = "localhost" # Alternate hostname (set same as hostname if not needed)